// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace App2.Google.Translate
{

    public class Translation
    {

        [JsonProperty("translatedText")]
        public string TranslatedText { get; set; }
    }

    public class Data
    {

        [JsonProperty("translations")]
        public Translation[] Translations { get; set; }
    }

    public class translations
    {

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

}