// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace App2.Google.NaturalLanguage.AnalyzeSentiment
{

    public class DocumentSentiment
    {

        [JsonProperty("polarity")]
        public int Polarity { get; set; }

        [JsonProperty("magnitude")]
        public double Magnitude { get; set; }

        [JsonProperty("score")]
        public double Score { get; set; }
    }

    public class Text
    {

        [JsonProperty("content")]
        public string Content { get; set; }

        [JsonProperty("beginOffset")]
        public int BeginOffset { get; set; }
    }

    public class Sentiment
    {

        [JsonProperty("polarity")]
        public int Polarity { get; set; }

        [JsonProperty("magnitude")]
        public double Magnitude { get; set; }

        [JsonProperty("score")]
        public double Score { get; set; }
    }

    public class Sentence
    {

        [JsonProperty("text")]
        public Text Text { get; set; }

        [JsonProperty("sentiment")]
        public Sentiment Sentiment { get; set; }
    }

    public class analyzeSentiment
    {

        [JsonProperty("documentSentiment")]
        public DocumentSentiment DocumentSentiment { get; set; }

        [JsonProperty("language")]
        public string Language { get; set; }

        [JsonProperty("sentences")]
        public Sentence[] Sentences { get; set; }
    }

}