// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace App2.Google.NaturalLanguage.AnalyzeEntities
{

    public class Metadata
    {

        [JsonProperty("mid")]
        public string Mid { get; set; }

        [JsonProperty("wikipedia_url")]
        public string WikipediaUrl { get; set; }
    }

    public class Text
    {

        [JsonProperty("content")]
        public string Content { get; set; }

        [JsonProperty("beginOffset")]
        public int BeginOffset { get; set; }
    }

    public class Mention
    {

        [JsonProperty("text")]
        public Text Text { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public class Entity
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("metadata")]
        public Metadata Metadata { get; set; }

        [JsonProperty("salience")]
        public double Salience { get; set; }

        [JsonProperty("mentions")]
        public Mention[] Mentions { get; set; }
    }

    public class analyzeEntities
    {

        [JsonProperty("entities")]
        public Entity[] Entities { get; set; }

        [JsonProperty("language")]
        public string Language { get; set; }
    }

}