// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace App2.Google.Vision
{

    public class Vertex
    {

        [JsonProperty("x")]
        public int X { get; set; }

        [JsonProperty("y")]
        public int Y { get; set; }
    }

    public class BoundingPoly
    {

        [JsonProperty("vertices")]
        public Vertex[] Vertices { get; set; }
    }

    public class Vertex2
    {

        [JsonProperty("x")]
        public int X { get; set; }

        [JsonProperty("y")]
        public int Y { get; set; }
    }

    public class FdBoundingPoly
    {

        [JsonProperty("vertices")]
        public Vertex2[] Vertices { get; set; }
    }

    public class Position
    {

        [JsonProperty("x")]
        public double X { get; set; }

        [JsonProperty("y")]
        public double Y { get; set; }

        [JsonProperty("z")]
        public double Z { get; set; }
    }

    public class Landmark
    {

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("position")]
        public Position Position { get; set; }
    }

    public class FaceAnnotation
    {

        [JsonProperty("boundingPoly")]
        public BoundingPoly BoundingPoly { get; set; }

        [JsonProperty("fdBoundingPoly")]
        public FdBoundingPoly FdBoundingPoly { get; set; }

        [JsonProperty("landmarks")]
        public Landmark[] Landmarks { get; set; }

        [JsonProperty("rollAngle")]
        public double RollAngle { get; set; }

        [JsonProperty("panAngle")]
        public double PanAngle { get; set; }

        [JsonProperty("tiltAngle")]
        public double TiltAngle { get; set; }

        [JsonProperty("detectionConfidence")]
        public double DetectionConfidence { get; set; }

        [JsonProperty("landmarkingConfidence")]
        public double LandmarkingConfidence { get; set; }

        [JsonProperty("joyLikelihood")]
        public string JoyLikelihood { get; set; }

        [JsonProperty("sorrowLikelihood")]
        public string SorrowLikelihood { get; set; }

        [JsonProperty("angerLikelihood")]
        public string AngerLikelihood { get; set; }

        [JsonProperty("surpriseLikelihood")]
        public string SurpriseLikelihood { get; set; }

        [JsonProperty("underExposedLikelihood")]
        public string UnderExposedLikelihood { get; set; }

        [JsonProperty("blurredLikelihood")]
        public string BlurredLikelihood { get; set; }

        [JsonProperty("headwearLikelihood")]
        public string HeadwearLikelihood { get; set; }
    }

    public class Vertex3
    {

        [JsonProperty("x")]
        public int X { get; set; }

        [JsonProperty("y")]
        public int Y { get; set; }
    }

    public class BoundingPoly2
    {

        [JsonProperty("vertices")]
        public Vertex3[] Vertices { get; set; }
    }

    public class LatLng
    {

        [JsonProperty("latitude")]
        public double Latitude { get; set; }

        [JsonProperty("longitude")]
        public double Longitude { get; set; }
    }

    public class Location
    {

        [JsonProperty("latLng")]
        public LatLng LatLng { get; set; }
    }

    public class LandmarkAnnotation
    {

        [JsonProperty("mid")]
        public string Mid { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("score")]
        public double Score { get; set; }

        [JsonProperty("boundingPoly")]
        public BoundingPoly2 BoundingPoly { get; set; }

        [JsonProperty("locations")]
        public Location[] Locations { get; set; }
    }

    public class Vertex4
    {

        [JsonProperty("x")]
        public int X { get; set; }

        [JsonProperty("y")]
        public int Y { get; set; }
    }

    public class BoundingPoly3
    {

        [JsonProperty("vertices")]
        public Vertex4[] Vertices { get; set; }
    }

    public class LogoAnnotation
    {

        [JsonProperty("mid")]
        public string Mid { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("score")]
        public double Score { get; set; }

        [JsonProperty("boundingPoly")]
        public BoundingPoly3 BoundingPoly { get; set; }
    }

    public class LabelAnnotation
    {

        [JsonProperty("mid")]
        public string Mid { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("score")]
        public double Score { get; set; }
    }

    public class Vertex5
    {

        [JsonProperty("x")]
        public int X { get; set; }

        [JsonProperty("y")]
        public int Y { get; set; }
    }

    public class BoundingPoly4
    {

        [JsonProperty("vertices")]
        public Vertex5[] Vertices { get; set; }
    }

    public class TextAnnotation
    {

        [JsonProperty("locale")]
        public string Locale { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("boundingPoly")]
        public BoundingPoly4 BoundingPoly { get; set; }
    }

    public class SafeSearchAnnotation
    {

        [JsonProperty("adult")]
        public string Adult { get; set; }

        [JsonProperty("spoof")]
        public string Spoof { get; set; }

        [JsonProperty("medical")]
        public string Medical { get; set; }

        [JsonProperty("violence")]
        public string Violence { get; set; }
    }

    public class Color2
    {

        [JsonProperty("red")]
        public int Red { get; set; }

        [JsonProperty("green")]
        public int Green { get; set; }

        [JsonProperty("blue")]
        public int Blue { get; set; }
    }

    public class Color
    {

        [JsonProperty("color")]
        public Color2 color { get; set; }

        [JsonProperty("score")]
        public double Score { get; set; }

        [JsonProperty("pixelFraction")]
        public double PixelFraction { get; set; }
    }

    public class DominantColors
    {

        [JsonProperty("colors")]
        public Color[] Colors { get; set; }
    }

    public class ImagePropertiesAnnotation
    {

        [JsonProperty("dominantColors")]
        public DominantColors DominantColors { get; set; }
    }

    public class Respons
    {

        [JsonProperty("faceAnnotations")]
        public FaceAnnotation[] FaceAnnotations { get; set; }

        [JsonProperty("landmarkAnnotations")]
        public LandmarkAnnotation[] LandmarkAnnotations { get; set; }

        [JsonProperty("logoAnnotations")]
        public LogoAnnotation[] LogoAnnotations { get; set; }

        [JsonProperty("labelAnnotations")]
        public LabelAnnotation[] LabelAnnotations { get; set; }

        [JsonProperty("textAnnotations")]
        public TextAnnotation[] TextAnnotations { get; set; }

        [JsonProperty("safeSearchAnnotation")]
        public SafeSearchAnnotation SafeSearchAnnotation { get; set; }

        [JsonProperty("imagePropertiesAnnotation")]
        public ImagePropertiesAnnotation ImagePropertiesAnnotation { get; set; }
    }

    public class annotate
    {

        [JsonProperty("responses")]
        public Respons[] Responses { get; set; }
    }

}