// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace App2.Google.Speech
{

    public class Alternative
    {

        [JsonProperty("transcript")]
        public string Transcript { get; set; }

        [JsonProperty("confidence")]
        public double Confidence { get; set; }
    }

    public class Result
    {

        [JsonProperty("alternatives")]
        public Alternative[] Alternatives { get; set; }
    }

    public class SpeechV1Beta1Results
    {

        [JsonProperty("results")]
        public Result[] Results { get; set; }
    }

}